FROM nvcr.io/nvidia/cuda:12.3.1-devel-ubuntu22.04
RUN apt-get update && apt-get install -y python3-pip libgl1-mesa-glx libglib2.0-0 && pip install tensorflow[and-cuda] opencv-python matplotlib seaborn
RUN pip install tensorflow==2.15.1
WORKDIR /home
COPY ./docker_components /home
ENV CUDNN_PATH="/usr/local/lib/python3.10/dist-packages/nvidia/cudnn"
ENV LD_LIBRARY_PATH="${CUDNN_PATH}/lib:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
