FROM nvcr.io/nvidia/l4t-base:r32.7.1

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
		build-essential \
		software-properties-common \
		apt-transport-https \
		ca-certificates \
		lsb-release \
		pkg-config \
		gnupg \
		git \
		libb64-0d \
		libre2-* \
		libssl-dev \
		rapidjson-dev \
		libopenblas-dev \
		libarchive-dev \
		zlib1g \
		curl \
		jq \
		wget \
		curl \
		nano \
		zip \
		python3-dev \
		python3-pip \
		unzip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN gcc --version && \
    g++ --version

RUN wget https://github.com/triton-inference-server/server/releases/download/v2.19.0/tritonserver2.19.0-jetpack4.6.1.tgz && \
    tar -xzf tritonserver2.19.0-jetpack4.6.1.tgz && \
    rm tritonserver2.19.0-jetpack4.6.1.tgz && \
    ls -lah

RUN mkdir /opt/bin && \
		mv /bin/tritonserver /opt/bin/tritonserver && \
		mv /bin/multi_server /opt/bin/multi_server && \
		mv /bin/memory_alloc /opt/bin/memory_alloc && \
		mv /bin/simple /opt/bin/simple 

RUN pip3 install --upgrade --no-cache-dir pip setuptools
RUN pip3 install --upgrade --no-cache-dir wheel==0.37.1 grpcio-tools numpy attrdict pillow
 
RUN mkdir -p /opt/tritonserver/backends && cp -r ./backends/* /opt/tritonserver/backends/

ENTRYPOINT ["/opt/bin/tritonserver"]